import { Types } from "mongoose";

export type TToLetListings = {
  propertyType: "family" | "sublet" | "office";
  bedroom: number;
  bathroom: number;
  balcony: number;
  size?: number;
  availability: string;
  floor: number;
  description?: string;
  address: string;
  thana: string;
  district: string;
  division: string;
  latitude: number;
  longitude: number;
  rent: number;
  advance: number;
  noticePeriod: number;
  electricity: boolean | null;
  gas: boolean | null;
  water: boolean | null;
  rentNegotiable?: boolean | null;
  internet: boolean | null;
  security: boolean | null;
  swimmingPool: boolean | null;
  furnished: boolean | null;
  parking: boolean | null;
  intercom: boolean | null;
  childrenPlayArea: boolean | null;
  lift: boolean | null;
  servantQuarter: boolean | null;
  waterHeater: boolean | null;
  generator: boolean | null;
  fitnessCenter: boolean | null;
  ac: boolean | null;
  ownerName: string;
  ownerEmail: string;
  phone: string;
  preferredContact: "phoneCall" | "email" | "whatsapp";
  propertyImages: string[];
  owner: Types.ObjectId;
};
