export type TToLetListings = {
  propertyType: "family" | "sublet" | "office";
  bedroom: number;
  bathroom: number;
  balcony: number;
  size?: number;
  availability: string;
  description?: string;
  street?: string;
  city: string;
  district: string;
  area: string;
  rent: number;
  advance: number;
  noticePeriod: number;
  electricity: boolean | null;
  gas: boolean | null;
  water: boolean | null;
  rentNegotiable?: boolean | null;
  internet: boolean | null;
  security: boolean | null;
  swimmingPool: boolean | null;
  furnished: boolean | null;
  parking: boolean | null;
  intercom: boolean | null;
  childrenPlayArea: boolean | null;
  lift: boolean | null;
  servantQuarter: boolean | null;
  waterHeater: boolean | null;
  generator: boolean | null;
  fitnessCenter: boolean | null;
  ac: boolean | null;
  ownerName: string;
  ownerEmail: string;
  phone: string;
  preferredContact: "phoneCall" | "email" | "whatsapp";
  propertyImages: string[];
};
